### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Matterhorn777**
Just a test file upload. Attempt to add comments to uploaded file. Today I will attempt to take the measurements of the 200L plastic drum blue hdpe chemical barrel 1600250834832 from alibaba example link and recreate in FreeCAD 2D then into 3D by creating a Datum Plane with a Pocket design thereby recreating the drum in a halved 3D "empty" vessel image. I will then align the mm standard measurments from Freecad to the Weir measurments in ideal and less than ideal situations. 2 weirs with 2 halved barrels based on the construction of concrete with plastic 'set' into weir central opening.

### CODE REVIEW

**Comment by maltfield** [comment]
I do not want to add an iPhone holder to this repo. But otherwise you can acknowledge  your test as successful.

**Comment by maltfield** [comment]
Also, before I checked the file list, I did some googling about how to diff a FreeCAD file. I found these threads on the FreeCAD forums:

 * https://forum.freecad.org/viewtopic.php?style=10&t=2334&sid=440d3c8a4cdd7a3b030d00a2396ead30&start=20
 *  https://forum.freecad.org/viewtopic.php?p=707486#p707486
 
 And tried this repo:

 * https://github.com/khimaros/freecad-build

Unfortunately I had an error with the diff (even though they should be the same file) so I opened this bug report

 * https://github.com/khimaros/freecad-build/issues/1

**Comment by Matterhorn777** [comment]
HDPE 200L Barrel is 590mm width X 930 mm height. diameter of existing opening has an aperture of 55mm X2 openings. weight 9.5 kg.

**Comment by Matterhorn777** [comment]
Added an expanded metal mesh plate to lay on open barrel's face and a wedge.
intake-Edit3

**Comment by maltfield** [comment]
@Matterhorn777 I can't see the changes that you've made as reflected in the screenshot. Did you commit the changes and push them up to your repo?

 * https://github.com/Matterhorn777/life-line/tree/main

Note that this is a list of all the changes that GitHub has seen by you:

 * https://github.com/Matterhorn777/life-line/commits/main/

There's only 1 commit where you added a file named `I-Phone-Holder.FCStd`

Please commit & push your changes up to your repo so that others can see them and I can merge it. It's best-practice to commit several times per day and push at least once per day.

**Pull request merged**
